spring:
  application:
    name: ribbon-example

server:
  port: 8888

ping-client:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9091,localhost:9092
    ServerListRefreshInterval: 15000